### ISSUE TITLE
Domain.ReadWrite.All incorrectly says that "This permission does not have any graph methods published."

### ISSUE THREAD

**Issue by cnotin** [merill/graph-permissions-explorer#8] opened 2023-12-05 18:04 UTC
The page for [Domain.ReadWrite.All](https://graphpermissions.merill.net/permission/Domain.ReadWrite.All) says that:
> This permission does not have any graph methods published

Whereas I can find at least those four MS Graph API that mention this permission:
* https://learn.microsoft.com/en-us/graph/api/domain-post-domains?view=graph-rest-1.0&tabs=http
* https://learn.microsoft.com/en-us/graph/api/domain-verify?view=graph-rest-1.0&tabs=http
* https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-1.0&tabs=http
* https://learn.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-1.0&tabs=http

So it seems that something is wrong ;)

**Comment by MartinM85** [comment] 2024-02-06 14:53
Seems like almost all permissions say the same.

**Comment by cnotin** [comment] 2024-02-06 14:55
Not all of them, for example https://graphpermissions.merill.net/permission/Device.Read.All

**Comment by MartinM85** [comment] 2024-02-06 15:08
I believe that the issue is somehow connected to permission tables in Graph API doc.
Some tables have two columns: https://learn.microsoft.com/en-us/graph/api/directoryobject-checkmembergroups?view=graph-rest-1.0&tabs=http#group-memberships-for-a-directory-object
Others have three columns: https://learn.microsoft.com/en-us/graph/api/domain-post-domains?view=graph-rest-1.0&tabs=http#permissions

I don't see any script how all pages are generated but I believe it parses data from GitHub repo for Graph API doc

**Comment by cnotin** [comment] 2024-02-06 15:11
That could explain it!

**Comment by merill** [comment] 2024-08-20 06:15
Thanks for raising this folks. Fixed now.

**Closed as completed** 2024-08-20 06:15 UTC
